version: '3.1'

services:
  db:
    image: mysql:8.0.33
    container_name: "db-container"
    restart: always
    environment:
      MYSQL_DATABASE: gerenciador_tarefas
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: "adminer-container"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db