version: '3.1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: gerenciador_tarefas
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: ./docker
    container_name: "fastapi-container"
    ports:
      - 8000:15400